# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI
# Portions of this file may implement 3GPP specifications, which may be subject to additional licensing requirements.

schema_version: 1

name: cu_up_appconfig
namespace: ocudu
description: cu-up application configuration
generate_header: false

outputs:
  header:       apps/cu_up/cu_up_appconfig.h
  cli11_source: apps/cu_up/cu_up_appconfig_cli11_schema.cpp
  cli11_header: apps/cu_up/cu_up_appconfig_cli11_schema.h

cli11_extra_includes:
  - '"apps/helpers/f1u/f1u_cli11_schema.h"'
  - '"apps/helpers/logger/logger_appconfig_cli11_schema.h"'
  - '"apps/helpers/network/sctp_cli11_schema.h"'
  - '"apps/helpers/tracing/tracer_appconfig_cli11_schema.h"'
  - '"apps/services/app_resource_usage/app_resource_usage_config_cli11_schema.h"'
  - '"apps/services/buffer_pool/buffer_pool_appconfig_cli11_schema.h"'
  - '"apps/services/metrics/metrics_config_cli11_schema.h"'
  - '"apps/services/remote_control/remote_control_appconfig_cli11_schema.h"'
  - '"apps/services/worker_manager/worker_manager_cli11_schema.h"'

cli11_source_preamble: |
  static void configure_cli11_e1ap_args(CLI::App& app, ocuup::e1ap_appconfig& e1ap_params)
  {
    app.add_option(
           "--addrs,--cu_cp_addr", // TODO: old name kept for backward compatibility, should be removed in the future
           e1ap_params.cu_cp_addresses,
           "CU-CP addresses to be used for E1 interface. Multiple addresses can be specified for SCTP multi-homing")
        ->capture_default_str();
    app.add_option(
           "--bind_addrs,--bind_addr", // TODO: old name kept for backward compatibility, should be removed in the future
           e1ap_params.bind_addresses,
           "CU-UP bind addresses to be used for E1 interface. Multiple addresses can be specified for SCTP "
           "multi-homing. If left empty, implicit bind is performed")
        ->capture_default_str();
    configure_cli11_sctp_socket_args(app, e1ap_params.sctp);
  }

cli11:
  function: configure_cli11_with_cu_appconfig_schema
  post_configure_raw: |
    app.add_flag("--dryrun", config.enable_dryrun, "Enable application dry run mode")->capture_default_str();
    configure_cli11_with_logger_appconfig_schema(app, config.log_cfg);
    configure_cli11_with_tracer_appconfig_schema(app, config.trace_cfg);
    configure_cli11_with_buffer_pool_appconfig_schema(app, config.buffer_pool_config);
    configure_cli11_with_worker_manager_appconfig_schema(app, config.expert_execution_cfg);
    configure_cli11_with_remote_control_appconfig_schema(app, config.remote_control_config);
    app_services::configure_cli11_with_app_resource_usage_config_schema(app, config.metrics_cfg.rusage_config);
    app_services::configure_cli11_with_metrics_appconfig_schema(app, config.metrics_cfg.metrics_service_cfg);
    CLI::App* cu_up_subcmd = add_subcommand(app, "cu_up", "CU-UP parameters")->configurable();
    CLI::App* e1ap_subcmd  = add_subcommand(*cu_up_subcmd, "e1ap", "E1AP parameters")->configurable();
    configure_cli11_e1ap_args(*e1ap_subcmd, config.e1ap_cfg);
    CLI::App* f1u_subcmd   = add_subcommand(*cu_up_subcmd, "f1u", "F1-U parameters")->configurable();
    configure_cli11_f1u_sockets_args(*f1u_subcmd, config.f1u_cfg);
