# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI
# Portions of this file may implement 3GPP specifications, which may be subject to additional licensing requirements.

schema_version: 1

name: du_low_appconfig
namespace: ocudu
description: du low application configuration
generate_header: false

outputs:
  header:       apps/du_low/du_low_appconfig.h
  cli11_source: apps/du_low/du_low_appconfig_cli11_schema.cpp
  cli11_header: apps/du_low/du_low_appconfig_cli11_schema.h

cli11_extra_includes:
  - '"apps/helpers/hal/hal_appconfig_extra.h"'
  - '"apps/helpers/hal/hal_cli11_schema.h"'
  - '"apps/helpers/logger/logger_appconfig_cli11_schema.h"'
  - '"apps/helpers/tracing/tracer_appconfig_cli11_schema.h"'
  - '"apps/services/app_execution_metrics/executor_metrics_config_cli11_schema.h"'
  - '"apps/services/app_resource_usage/app_resource_usage_config_cli11_schema.h"'
  - '"apps/services/metrics/metrics_config_cli11_schema.h"'
  - '"apps/services/remote_control/remote_control_appconfig_cli11_schema.h"'
  - '"apps/services/worker_manager/worker_manager_cli11_schema.h"'

cli11:
  function: configure_cli11_with_du_low_appconfig_schema
  post_configure_raw: |
    app.add_flag("--dryrun", config.enable_dryrun, "Enable application dry run mode")->capture_default_str();
    configure_cli11_with_logger_appconfig_schema(app, config.log_cfg);
    configure_cli11_with_tracer_appconfig_schema(app, config.trace_cfg);
    configure_cli11_with_worker_manager_appconfig_schema(app, config.expert_execution_cfg);
    app_services::configure_cli11_with_executor_metrics_appconfig_schema(app, config.metrics_cfg.executors_metrics_cfg);
    app_services::configure_cli11_with_app_resource_usage_config_schema(app, config.metrics_cfg.rusage_config);
    app_services::configure_cli11_with_metrics_appconfig_schema(app, config.metrics_cfg.metrics_service_cfg);
    configure_cli11_with_remote_control_appconfig_schema(app, config.remote_control_config);
    #ifdef DPDK_FOUND
    config.hal_config.emplace();
    configure_cli11_with_hal_appconfig_schema(app, *config.hal_config);
    #else
    app.failure_message([](const CLI::App* application, const CLI::Error& e) -> std::string {
      if (std::string(e.what()).find("INI was not able to parse hal.++") == std::string::npos) {
        return CLI::FailureMessage::simple(application, e);
      }
      return "Invalid configuration detected, 'hal' section is present but the application was built without DPDK "
             "support\n" +
             CLI::FailureMessage::simple(application, e);
    });
    #endif
