cu_cp:
  amf:
    addr: 192.168.200.207
    port: 38412
    bind_addr: 192.168.200.205
    supported_tracking_areas:
      - tac: 1
        plmn_list:
          - plmn: "99970"
            tai_slice_support_list:
              - sst: 1

ru_sdr:
  device_driver: zmq
  device_args: tx_port=tcp://127.0.0.1:2000,rx_port=tcp://127.0.0.1:2001,base_srate=11.52e6
  srate: 11.52
  tx_gain: 0
  rx_gain: 0

cell_cfg:
  dl_arfcn: 368500
  band: 3
  channel_bandwidth_MHz: 10
  common_scs: 15
  plmn: "99970"
  tac: 1
  pci: 1
  nof_antennas_dl: 1
  nof_antennas_ul: 1
  pdsch:
    mcs_table: qam64
  pusch:
    mcs_table: qam64
  pdcch:
    dedicated:
      ss2_type: common
      dci_format_0_1_and_1_1: false
  prach:
    prach_config_index: 1

expert_execution:
  threads:
    main_pool:
      nof_threads: 4
    lower_phy:
      execution_profile: single

log:
  filename: /tmp/gnb.log
  all_level: warning

pcap:
  ngap_enable: false
