cu_cp:
  amf:
    addrs: 192.168.200.207
    port: 38412
    bind_addrs: 192.168.200.213
    supported_tracking_areas:
      - tac: 1
        plmn_list:
          - plmn: "99942"
            tai_slice_support_list:
              - sst: 1

ru_sdr:
  device_driver: uhd
  device_args: type=b200,serial=31E9F80 # another first used usrp: 31E9F18 
  srate: 23.04   #23.04 for 20mhz bw, 15.36 for 10 mhz
  otw_format: sc12
  tx_gain: 88
  rx_gain: 50
  clock: external

cell_cfg:
  dl_arfcn: 650000
  band: 78
  channel_bandwidth_MHz: 20
  common_scs: 30
  plmn: "99942"
  tac: 1
  pci: 1
  nof_antennas_dl: 1
  nof_antennas_ul: 1

expert_execution:
  threads:
    main_pool:
      nof_threads: 4
    lower_phy:
      execution_profile: dual


log:
  filename: /tmp/gnb.log
  all_level: info

pcap:
  mac_enable: true
  mac_filename: /tmp/gnb_mac.pcap
  ngap_enable: true
  ngap_filename: /tmp/gnb_ngap.pcap
